# Generated by Django 5.1.3 on 2024-11-21 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='title',
            new_name='name',
        ),
    ]
